<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<NoWarn>CS3002,CS3001,CS3003</NoWarn>
		<LangVersion>12.0</LangVersion>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>sixnet.snk</AssemblyOriginatorKeyFile>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<FileVersion>2.0.0.0</FileVersion>
		<Version>2.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.14.0" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.DirectoryServices.Protocols" Version="9.0.10" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.10" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
		<PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
		<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.10" />
		<PackageReference Include="System.Threading.Channels" Version="9.0.10" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Linq" />
		<Using Include="System.Linq.Expressions" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Linq.Expressions.Expression" Static="true" />
		<Using Include="AutoMapper.Execution.ExpressionBuilder" Static="true" />
	</ItemGroup>
</Project>
