<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
		<NoWarn>CS3002,CS3001,CS3003</NoWarn>
		<LangVersion>12.0</LangVersion>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>sixnet.snk</AssemblyOriginatorKeyFile>
		<Title>$(AssemblyName)</Title>
		<Authors>DingBin.Li</Authors>
		<Owners>DingBin.Li</Owners>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/sixnet-net</PackageProjectUrl>
		<Copyright>Copyright © DingBin.Li</Copyright>
		<PackageTags>.NET;Sixnet;DDD</PackageTags>
		<Description>A simple, easy-to-use, flexible, and efficient .NET development framework</Description>
		<PackageIcon>nugeticon.png</PackageIcon>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\nugeticon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.9" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.1" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Linq" />
		<Using Include="System.Linq.Expressions" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Linq.Expressions.Expression" Static="true" />
		<Using Include="AutoMapper.Execution.ExpressionBuilder" Static="true" />
	</ItemGroup>
</Project>
