<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
		<NoWarn>CS3002,CS3001,CS3003</NoWarn>
		<LangVersion>12.0</LangVersion>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>sixnet.snk</AssemblyOriginatorKeyFile>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<FileVersion>2.0.0.0</FileVersion>
		<Version>2.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.9" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.19.1" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Linq" />
		<Using Include="System.Linq.Expressions" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Linq.Expressions.Expression" Static="true" />
		<Using Include="AutoMapper.Execution.ExpressionBuilder" Static="true" />
	</ItemGroup>
</Project>
